#!/bin/bash

echo "Copying local migrations to container"
echo "Note: you can also just run docker-compose up --build, but that takes longer if you already have the container built"

docker cp ../schema database_container:/root/